wandb_version: 1

model:
  desc: null
  value: Segdiff
dataset:
  desc: null
  value: ISIC
epochs:
  desc: null
  value: 1
image_size:
  desc: null
  value: 128
channel:
  desc: null
  value: 1
batch_size:
  desc: null
  value: 4
learning_rate:
  desc: null
  value: 0.0001
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1716183882.0
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.10.12
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
